(() => {
  const buildImage = (path, file, width) =>
    `https://upload.wikimedia.org/wikipedia/commons/thumb/${path}/${file}/${width}px-${file}`;

  const makeImage = (path, file, alt) => ({
    src: buildImage(path, file, 1400),
    srcset: `${buildImage(path, file, 900)} 900w, ${buildImage(path, file, 1400)} 1400w`,
    thumb: buildImage(path, file, 200),
    thumbSrcset: `${buildImage(path, file, 200)} 200w, ${buildImage(path, file, 400)} 400w`,
    alt,
  });

  const vehicles = {
    "range-rover-sport": {
      id: "range-rover-sport",
      name: "Range Rover Sport",
      trim: "Autobiography",
      year: "2022",
      price: "KES 18.5M",
      priceValue: 18500000,
      mileage: "38,000 KM",
      engine: "3.0L SDV6 / 3000cc",
      power: "340 hp / 700 Nm",
      transmission: "8-Speed Automatic",
      drivetrain: "AWD / Terrain Response 2",
      exterior: "Fuji White / Black Pack",
      interior: "Ebony Windsor Leather",
      fuel: "Diesel",
      stockId: "RRC-2241",
      vinStatus: "Verified",
      logbook: "Ready",
      warranty: "12 Months",
      location: "Nairobi",
      images: [
        makeImage("5/54", "Land_Rover_RANGE_ROVER_SPORT_HSE_(L494)_front.jpg", "Range Rover Sport Autobiography front"),
        makeImage("9/9d", "Land_Rover_RANGE_ROVER_SPORT_HSE_(L494)_rear.jpg", "Range Rover Sport rear"),
        makeImage("9/9f", "Land_Rover_RANGE_ROVER_SPORT_HSE_(L494)_interior.jpg", "Range Rover Sport interior"),
        makeImage("f/fe", "2014_Land_Rover_Range_Rover_Autobiography_5.0_Front.jpg", "Range Rover Autobiography detail"),
      ],
      similar: ["range-rover-velar", "range-rover-autobiography", "defender-110"],
    },
    "range-rover-velar": {
      id: "range-rover-velar",
      name: "Range Rover Velar",
      trim: "R-Dynamic",
      year: "2021",
      price: "KES 14.2M",
      priceValue: 14200000,
      mileage: "52,000 KM",
      engine: "2.0L Si4 / 2000cc",
      power: "247 hp / 365 Nm",
      transmission: "8-Speed Automatic",
      drivetrain: "AWD / Terrain Response",
      exterior: "Silicon Silver / Black Contrast",
      interior: "Ebony Leather",
      fuel: "Petrol",
      stockId: "RRC-2197",
      vinStatus: "Verified",
      logbook: "In transit",
      warranty: "6 Months",
      location: "Import stock",
      images: [
        makeImage("9/9d", "2017_Land_Rover_Range_Rover_Velar_First_Edition_D3_3.0_Front.jpg", "Range Rover Velar front"),
        makeImage("5/54", "Land_Rover_RANGE_ROVER_SPORT_HSE_(L494)_front.jpg", "Range Rover detail"),
        makeImage("9/9f", "Land_Rover_RANGE_ROVER_SPORT_HSE_(L494)_interior.jpg", "Range Rover interior"),
        makeImage("7/7b", "Land_Rover_RANGE_ROVER_VOGUE_(ABA-LG3SB)_front.jpg", "Range Rover Vogue detail"),
      ],
      similar: ["range-rover-sport", "range-rover-vogue", "defender-110"],
    },
    "range-rover-autobiography": {
      id: "range-rover-autobiography",
      name: "Range Rover",
      trim: "Autobiography",
      year: "2014",
      price: "KES 21.5M",
      priceValue: 21500000,
      mileage: "62,000 KM",
      engine: "5.0L V8 / 5000cc",
      power: "510 hp / 625 Nm",
      transmission: "8-Speed Automatic",
      drivetrain: "AWD / Terrain Response 2",
      exterior: "Santorini Black / Shadow Pack",
      interior: "Ivory leather",
      fuel: "Petrol",
      stockId: "RRC-2033",
      vinStatus: "Verified",
      logbook: "Ready",
      warranty: "12 Months",
      location: "Nairobi",
      images: [
        makeImage("f/fe", "2014_Land_Rover_Range_Rover_Autobiography_5.0_Front.jpg", "Range Rover Autobiography front"),
        makeImage("5/54", "Land_Rover_RANGE_ROVER_SPORT_HSE_(L494)_front.jpg", "Range Rover detail"),
        makeImage("9/9f", "Land_Rover_RANGE_ROVER_SPORT_HSE_(L494)_interior.jpg", "Range Rover interior"),
        makeImage("7/7b", "Land_Rover_RANGE_ROVER_VOGUE_(ABA-LG3SB)_front.jpg", "Range Rover Vogue detail"),
      ],
      similar: ["range-rover-vogue", "range-rover-sport", "defender-110"],
    },
    "range-rover-vogue": {
      id: "range-rover-vogue",
      name: "Range Rover Vogue",
      trim: "SE",
      year: "2017",
      price: "KES 17.5M",
      priceValue: 17500000,
      mileage: "64,000 KM",
      engine: "4.4L SDV8 / 4400cc",
      power: "339 hp / 740 Nm",
      transmission: "8-Speed Automatic",
      drivetrain: "AWD / Terrain Response 2",
      exterior: "Santorini Black / Privacy glass",
      interior: "Ebony leather",
      fuel: "Diesel",
      stockId: "RRC-2112",
      vinStatus: "Verified",
      logbook: "Ready",
      warranty: "6 Months",
      location: "Nairobi",
      images: [
        makeImage("7/7b", "Land_Rover_RANGE_ROVER_VOGUE_(ABA-LG3SB)_front.jpg", "Range Rover Vogue front"),
        makeImage("5/54", "Land_Rover_RANGE_ROVER_SPORT_HSE_(L494)_front.jpg", "Range Rover detail"),
        makeImage("9/9f", "Land_Rover_RANGE_ROVER_SPORT_HSE_(L494)_interior.jpg", "Range Rover interior"),
        makeImage("f/fe", "2014_Land_Rover_Range_Rover_Autobiography_5.0_Front.jpg", "Range Rover Autobiography detail"),
      ],
      similar: ["range-rover-sport", "range-rover-autobiography", "range-rover-classic"],
    },
    "range-rover-classic": {
      id: "range-rover-classic",
      name: "Range Rover Vogue",
      trim: "Classic",
      year: "2000",
      price: "KES 4.8M",
      priceValue: 4800000,
      mileage: "160,000 KM",
      engine: "4.6L V8 / 4600cc",
      power: "222 hp / 380 Nm",
      transmission: "Automatic",
      drivetrain: "4WD",
      exterior: "Oxford Green",
      interior: "Tan leather",
      fuel: "Petrol",
      stockId: "RRC-1874",
      vinStatus: "Verified",
      logbook: "Ready",
      warranty: "3 Months",
      location: "Nairobi",
      images: [
        makeImage("f/ff", "2000_Land_Rover_Range_Rover_Vogue_Automatic_4.6_Front.jpg", "Range Rover Classic front"),
        makeImage("7/7b", "Land_Rover_RANGE_ROVER_VOGUE_(ABA-LG3SB)_front.jpg", "Range Rover Vogue detail"),
        makeImage("9/9f", "Land_Rover_RANGE_ROVER_SPORT_HSE_(L494)_interior.jpg", "Range Rover interior"),
        makeImage("5/54", "Land_Rover_RANGE_ROVER_SPORT_HSE_(L494)_front.jpg", "Range Rover detail"),
      ],
      similar: ["range-rover-vogue", "defender-110", "range-rover-sport"],
    },
    "defender-110": {
      id: "defender-110",
      name: "Defender 110",
      trim: "SE",
      year: "2020",
      price: "KES 19.8M",
      priceValue: 19800000,
      mileage: "44,000 KM",
      engine: "3.0L D300 / 3000cc",
      power: "296 hp / 650 Nm",
      transmission: "8-Speed Automatic",
      drivetrain: "AWD / Terrain Response",
      exterior: "Pangea Green",
      interior: "Ebony grained leather",
      fuel: "Diesel",
      stockId: "RRC-2278",
      vinStatus: "Verified",
      logbook: "In transit",
      warranty: "6 Months",
      location: "Import stock",
      images: [
        makeImage("a/a3", "Land_Rover_Defender_(L663)_IMG_4267.jpg", "Land Rover Defender 110 front"),
        makeImage("5/54", "Land_Rover_RANGE_ROVER_SPORT_HSE_(L494)_front.jpg", "Range Rover detail"),
        makeImage("9/9f", "Land_Rover_RANGE_ROVER_SPORT_HSE_(L494)_interior.jpg", "Range Rover interior"),
        makeImage("7/7b", "Land_Rover_RANGE_ROVER_VOGUE_(ABA-LG3SB)_front.jpg", "Range Rover Vogue detail"),
      ],
      similar: ["range-rover-sport", "range-rover-velar", "range-rover-vogue"],
    },
  };

  window.RRC_VEHICLES = vehicles;
})();

